
levels = {
    intro:[{
            X:180,
            y:384,
            text:'Hello!',
            choices:[
                "Ok...",
                "No...",
                "Yes...",
                "What?"
            ],
            events:[
                "end",
                "end",
                "end",
                "to"
            ],
        },
        {
            text:'Hey!',
            choices:[
                "Sure.",
                "Why...",
                "Alright...",
                "No way!"
            ],
            events:[
                "end",
                "end",
                "to",
                "end"
            ], 
        },
        {
            text:'Hey!',
            choices:[
                "Sure.",
                "Why...",
                "Alright...",
                "No way!"
            ],
            events:[
                "end",
                "end",
                "end",
                "end"
            ], 
        }] 
}
